window.QUIVER_CAST = [
  { symbol:"LOCKSLEY", name:"Robin of Locksley", img:"img/mark.svg", role:"First shaft",
    lore:"Outlawed from the hall, he takes to Sherwood and becomes the string the band hangs from. $QUIVER is the case; LOCKSLEY is the first arrow loosed from it." },
  { symbol:"MARIAN", name:"Maid Marian", img:"img/mark.svg", role:"Ally of the wood",
    lore:"Not a prize and not a guest. She stands with the wood as a shaft in her own right — courage counted equal to the longbow." },
  { symbol:"JOHN", name:"Little John", img:"img/mark.svg", role:"The tall string",
    lore:"Named in irony. Quarterstaff before the longbow. When the band needs a bridge across a stream, it is John who holds both banks." },
  { symbol:"TUCK", name:"Friar Tuck", img:"img/mark.svg", role:"Blesses the nock",
    lore:"A friar who keeps the larder honest and the fire lit. Next unused name after the opening four. He drinks the fee and calls it tithe." },
  { symbol:"SCARLET", name:"Will Scarlet", img:"img/mark.svg", role:"Loud cloth",
    lore:"Scarlet was expensive dyed cloth. He is the bright cut in a green band — temper, flash, and a second bow when Locksley is elsewhere." },
  { symbol:"MUCH", name:"Much the Miller", img:"img/mark.svg", role:"Keeps the larder",
    lore:"The miller's son. Grain, sacks, and the quiet work that lets the others play hero. In QUIVER he is the larder made visible." },
  { symbol:"ALAN", name:"Alan-a-Dale", img:"img/mark.svg", role:"Voice on the road",
    lore:"Minstrel of the Great North Road. He carries news the Sheriff would rather stay unsaid. A shaft that spreads the song, not the steel." },
  { symbol:"SHERWOOD", name:"Sherwood", img:"img/mark.svg", role:"The wood itself",
    lore:"Shire-wood: the woodland belonging to the county, and a second law beside the road. After hours never closes." },
  { symbol:"NOTTING", name:"Nottingham", img:"img/mark.svg", role:"The hunting town",
    lore:"Snotengaham — homestead of Snot's people. The town that hunts the wood. A quarry-facing shaft: the market outside the oaks." },
  { symbol:"GREEN", name:"Lincoln Green", img:"img/mark.svg", role:"The uniform",
    lore:"Cheap woodland cloth dyed in Lincoln. Not a person — the color that makes a band a band." },
  { symbol:"GISBORNE", name:"Guy of Gisborne", img:"img/mark.svg", role:"Hired steel",
    lore:"The bounty hunter in the popular cycle. A shaft loosed from the other side of the road. Still a meme with a quarry." },
  { symbol:"SHERIFF", name:"Sheriff of Nottingham", img:"img/mark.svg", role:"Near crown's hand",
    lore:"The office that keeps the forest law for the near prince. In QUIVER he is named so the wood remembers what it is hiding from." },
  { symbol:"RICHARD", name:"King Richard", img:"img/mark.svg", role:"The far crown",
    lore:"Lionheart, away on crusade in the popular telling. The far law. A shaft that does not live in the oaks, but the band still answers to the name." },
  { symbol:"PRINCE", name:"Prince John", img:"img/mark.svg", role:"The near crown",
    lore:"The tax and the temper while Richard is gone. Named so the forest has a near opposite, not a vacuum." },
  { symbol:"OAK", name:"Major Oak", img:"img/mark.svg", role:"Trysting tree",
    lore:"The meeting tree. Hollow trunk, gold moon. Where the band is called and where a nock is argued before it flies." },
  { symbol:"BOW", name:"Longbow", img:"img/mark.svg", role:"What the string is for",
    lore:"Yew, linen, and a hundred pounds of draw. The meter on the site is this object made into a rule: no nock until the draw is full." },
  { symbol:"HORN", name:"Hunting Horn", img:"img/mark.svg", role:"Call the band",
    lore:"Brass and leather on an oak limb. One note gathers the shafts. In the app, activity is the horn written down." }
];
window.QUIVER_BY = Object.fromEntries(window.QUIVER_CAST.map(c => [c.symbol, c]));
